{% set name = "demes" %}
{% set version = "0.2.0" %}
{% set sha256 = "2bc650cc0e60cebabc24bf00521a5833769f56b118f6ab44526e42171c961231" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - demes = demes.__main__:cli
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - setuptools_scm
    - pip

  run:
    - python >=3.6
    # pins taken from setup.cfg
    - attrs  >=20.3
    - ruamel.yaml >=0.15.78

test:
  imports:
    - demes
  commands:
    - pip check
    - demes --help
  requires:
    - pip

about:
  home: https://github.com/popsim-consortium/demes-python
  license: ISC
  license_family: BSD
  license_file: LICENSE
  summary: Tools for describing and manipulating demographic models in population genetics.
  doc_url: https://popsim-consortium.github.io/demes-docs/
  dev_url: https://github.com/popsim-consortium/demes-python

extra:
  recipe-maintainers:
    - jeromekelleher
    - grahamgower
