{% set name = "demes" %}
{% set version = "0.2.3" %}
{% set sha256 = "9e613b65b475dba277bca751de1f37a89fd5eb4d856ba27733a2099c8a823617" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  entry_points:
    - demes = demes.__main__:cli
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
    - pip

  run:
    - python >={{ python_min }}
    # pins taken from setup.cfg
    - attrs  >=20.3
    - ruamel.yaml >=0.15.78

test:
  imports:
    - demes
  commands:
    - pip check
    - demes --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/popsim-consortium/demes-python
  license: ISC
  license_family: BSD
  license_file: LICENSE
  summary: Tools for describing and manipulating demographic models in population genetics.
  doc_url: https://popsim-consortium.github.io/demes-docs/
  dev_url: https://github.com/popsim-consortium/demes-python

extra:
  recipe-maintainers:
    - jeromekelleher
    - grahamgower
